<<<<<<< HEAD
/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
=======
/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
>>>>>>> e7229e4e012fdb6b1d47d4d1f5ed600e2e5b7960

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
