<<<<<<< HEAD
/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
=======
/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
>>>>>>> e7229e4e012fdb6b1d47d4d1f5ed600e2e5b7960

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
